#+TITLE: AStA-Protokoll
#+SUBTITLE: Ungenehmigtes Protokoll der Sitzung am
#+DATE: 22.33.4444
#+LATEX_CLASS: report
#+LATEX_CLASS_OPTIONS: [a4paper]
#+LATEX_HEADER: \usepackage[ngerman]{babel}
#+LATEX_HEADER: \usepackage[top=3cm, bottom=3cm, left=3cm, right=3cm]{geometry}
#+LATEX_HEADER_EXTRA: \setcounter{tocdepth}{1}
#+LANGUAGE: de
#+OPTIONS: author:nil d:nil toc:nil


:HINWEISE:
Wir wünschen uns folgendes Sitzungsverhalten, damit die Sitzungen des AStAs angenehm sind und alle zu Wort kommen können:
- Achte auf deine Körpersprache.
- Respektiere die Rede- und Sitzungsleitung. Unterstütze sie, wenn sie Unterstützung braucht.
- Baue aktiv Wissenshierachien ab. Lass Raum für Rückfragen und achte auf Menschen mit weniger Wissen.
- Zeige anderen Redner*innen Respekt und störe diese nicht.
- Nimm Rücksicht auf deine Mitmenschen. Der AStA soll ein Schutzraum sein und Diskriminierungen entgegenwirken.
- Halte dich zurück, sollten Diskussionen emotional eskalieren. Setze auf Deeskalation und konstruktive Zusammenarbeit.

Link zum anonymen Fragen und Kummerkastenpad: https://pads.ccc.de/ffks3jTpji
:END:


\tableofcontents
\pagebreak

# hier beginnt das Protokoll

* Formalia
- Protokollführung: ::
- Sitzungsleitung: ::
- Beschlussfähigkeit: :: Mit XX von 11 benötigten Mitgliedern ist die Sitzung nicht beschlussfähig
# Anwesenheitsliste, nicht anwesende bitte löschen.
- Anwesende: :: /Antidiskriminierung, BIPoC*, Gender, Regenbogen, Studieren mit familiären Beziehungen, Studieren ohne Hürden, Erasmus und Auslandsstudium, Gegen Antisemitismus, Gegen Faschismus, Hochschulpolitik, Kommunikation und Wissenssicherung, Politische Bildung, PR, Presse, Sozial, Umwelt, Vorstand(C), Vorstand(D), Vorstand(J), Vorstand(L), Präsidium, Finanzstelle/
- Gäste: :: /Keine./
- Unbesetzte Referate :: /Außenreferat, Datenschutz, Kulturreferat, Tierrechte/
- Annahme des Protokolls vom XX.XX.2020: :: Ohne Anmerkungen angenommen.|Mit den folgenden Änderungen angenommen:
  - !Wenn keine Anmerkungen: Diese Zeile löschen!

*** Anmerkungen zur TO:
- /Keine./

* Berichte 
** Antidiskriminierung
- n/a

** BIPoC*
- n/a

** Gender
- n/a

** Regenbogen
- n/a

** Studieren mit familiären Verpflichtungen
- n/a

** Studieren ohne Hürden
- n/a

** Erasmus und Auslandsstudium
- n/a

** Gegen Antisemitismus
- n/a

** Gegen Faschismus
- n/a

** Hochschulpolitik
- n/a

** Kommunikation und Wissenssicherung
- n/a

** Lehramt
- n/a

** Politische Bildung
- n/a

** PR
- n/a

** Presse
- n/a

** Sozialreferat
- n/a

** Umwelt
- n/a

  
** Vorstand
-

** StuRa-Präsidium
-

** Sekki :noexport:
-

** Finanzstelle :noexport:
-


* Bewerbungen :noexport:

* Raumanträge

** <Titel (denkt euch bitte was aus)>

+ Gruppe: ::
+ Raum: ::
+ Termin: ::
+ Erklärung: ::

*** Diskussion:
- /Keine./

*** Abstimmung #:
(j/n/e) (#/#/#) => Der Antrag ist angenommen.|Der Antrag wurde abgelehnt.


* Finanzanträge

** <Titel (denkt euch bitte was aus)>

+ Antragssteller*innen: ::
+ Betrag: ::
+ Budget :: 
+ Erklärung: ::
    
*** Diskussion:
- /Keine./

*** Abstimmung #:
(j/n/e) (#/#/#) => Es wurden #€ bewilligt.|Der Antrag wurde abgelehnt.


* Planung und Diskussion
  
** <Titel>
:DISKUSSIONSZEIT:
Wie lange soll die Diskussion etwa dauern? ## Min
:END:
*** Beschreibung

*** Diskussion

* Sonstiges

** <Titel>

* Termine
- <Datum> <Uhrzeit>, <Ort> :: <weitere Infos>


\vspace{1.5cm}
=ENDE: XX:XX Uhr=

# Ab hier ist alles nicht mehr im Protokoll. Entsprechend muss auch nicht mitgeschrieben werden :)
* Feedbackrunde                                                    :noexport:
  
* Orga                                                             :noexport:
    Hier stehen Dinge, die man für die Orga braucht. Tauchen nicht im Protokoll auf, und müssen fast nur vom Vorstand angefasst werden.
    
** Protokoll

Wer schreibt hauptsächlich in der Sitzung mit? Nach oben kopieren, dann hier in die letzte Zeile stellen


Aus dem Pad der letzten Sitzung übernehmen!


** Sitzungs- und Redeleitung

Leitet die Sitzung und führt die Redeliste. Wird gleich gehandhabt wie beim Protokoll.
Wichtig: Protokoll und Redeliste sind nicht in Personalunion. Wenn es hier eine Kollission gibt, wird der nächste Punkt der Liste genommen.

Aus dem Pad der letzten Sitzung übernehmen!

